# Generated by Django 4.0.6 on 2022-08-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
