# Generated by Django 4.0.6 on 2022-08-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('files', models.FileField(blank=True, upload_to='')),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
